### ISSUE TITLE
Not able to train the PixelCNN

### ISSUE THREAD

**Issue by phmignot** [ritheshkumar95/pytorch-vqvae#9]
Hello, thanks for your work.
I am fighting some issues when training your models. I followed your [Instructions](https://github.com/ritheshkumar95/pytorch-vqvae#instructions).

First, I think you may have forgotten to add '--dataset' argument in both of your commands.
Then, I think you forget to import _datasets_ from _torchvision_ in pixelcnn_prior.py. 

Eventually, running:
> python3 pixelcnn_prior.py --data-folder /tmp/miniimagenet --output-folder models/vqvae --dataset mnist

results in: 
>AttributeError: 'MNIST' object has no attribute '_label_encoder'

And I have the same issue with CIFAR dataset.

**Comment by Tinemar** [comment]
Have you solved it? I got the same question.

**Comment by phmignot** [comment]
No sorry, I ended up just training a VqVae model on my data.

**Comment by Newbeeer** [comment]
changing n_classes=len(train_dataset._label_encoder) to num_classes=10 would be fine

**Comment by huangxiao1234** [comment]
> Hello, thanks for your work.
> I am fighting some issues when training your models. I followed your [Instructions](https://github.com/ritheshkumar95/pytorch-vqvae#instructions).
> 
> First, I think you may have forgotten to add '--dataset' argument in both of your commands.
> Then, I think you forget to import _datasets_ from _torchvision_ in pixelcnn_prior.py.
> 
> Eventually, running:
> 
> > python3 pixelcnn_prior.py --data-folder /tmp/miniimagenet --output-folder models/vqvae --dataset mnist
> 
> results in:
> 
> > AttributeError: 'MNIST' object has no attribute '_label_encoder'
> 
> And I have the same issue with CIFAR dataset.

I had the same problem with you in training. The author pixelcnn should only be used for miniimagenet, so import dataset is not needed

**Comment by prateekm08** [comment]
I replaced `__label_encoder` with `class_to_idx` and it works well. Hope this helps.

**Comment by hosegragon** [comment]
> I replaced `__label_encoder` with `class_to_idx` and it works well. Hope this helps.

thank you, it works
